### ISSUE TITLE
doHMRF error

### ISSUE THREAD

**Issue by yangxueqianR** [giotto-suite/Giotto#103]
Hello, I ran mini_seqfish.Rmd in your vignettes directory, everything went well before, but when I ran to doHMRF, the error showed that there was a lack of <blocks. txt> . I would like to ask if you have ever encountered such an error and how to solve it

**Comment by pacificma** [comment]
Hi, could you share us the full log message after you ran doHMRF function, and also the environment you were using (operation system/ R version/ Giotto version/....)? It might not due to the doHMRF function it self, since we have tested the function in different branches and works well on mac. But I had same issue with it on the windows10 platform.

**Comment by bernard2012** [comment]
Knowing the environment will help. If it is difficult to resolve, you could just use Giotto in Docker image, as this will take care of all environment related issues, pre-requisites, and is cross platform compatible.
