### ISSUE TITLE
Jackstraw method computed on genes rather than cells

### ISSUE THREAD

**Issue by nilseling** [giotto-suite/Giotto#19]
Hi,
 
could it be that the 'expr_values' matrix needs to be transposed here:
https://github.com/RubD/Giotto/blob/fefab049ce9747acd8a15d75ed67daa1ab16ebd3/R/dimension_reduction.R#L187

I guess the jackstraw permutations are performed on the genes rather than the cells at this point.
Best,

Nils

**Comment by RubD** [comment]
Hi Nils,

Thanks for your comment.

Here we wanted to identify which PCs (based on genes) should be used to cluster cells downstream. In order to identify stable (or significant) PCs the jackstraw method randomly and iteratively permutes a set of genes and then computes how this affects each PC. So following this logic it seems that permutations on genes is correct, right?

Best,
Ruben

**Comment by nilseling** [comment]
Hi Ruben,
hmm, maybe I'm confused. For me the jackstraw method only returns a comparable result to signPCA(gobject, method = "screeplot") when transposing the matrix. But I only had a quick look and might have to think about this further.
Best,
Nils
