### ISSUE TITLE
PR proposal: conversion to Bioconductor *Experiment classes

### ISSUE THREAD

**Issue by andrewrech** [giotto-suite/Giotto#284]
Hi all,

Will you accept a PR on `suite` for conversion between the Bioconductor *Experiment classes?

I've hacked this together for my work and it doesn't seem too hard to generalize... maybe.

I'd probably take a similar approach to how you convert for MAST, dropping the Giotto fields that do not map cleanly, so it'd be a one-way conversion. *Experiment to Giotto could probably be lossless in most cases. Updating Giotto from *Experiment might also work but it could get complicated.

Another option is to go through Seurat.

I'd aim for some time in August. If this sounds like something on your roadmap, please let me know design thoughts.

Thanks

**Comment by RubD** [comment]
Hi @andrewrech 

Yes, that would certainly be welcome and thanks for the suggestion. We have actually discussed this at some point since we would like to connect Giotto better with the Bioconductor classes and pipelines. 

I also agree with you that it should be pretty straightforward and  happy to discuss this in more detail with you.

Which Giotto version are you currently using?

Ruben

**Comment by andrewrech** [comment]
Hi Ruben,

Thanks for your response. I'll give the implemenation some more thought and reach out.

I'm using the latest commit on the suite branch (with a bunch of data sources - CODEX, 10x, and NSTG protein, CTA, WTA and CosMX).

**Comment by RubD** [comment]
Hi Andrew,

In case you missed this, a talented new BU graduate student @irzamsarfraz made a first prototype to convert between the Giotto and spatialExperiment classes.

See https://github.com/RubD/Giotto/pull/312 for more info.

Ruben
