### ISSUE TITLE
Selecting k in 'clusterSpatialCorGenes'

### ISSUE THREAD

**Issue by daccachejoe** [giotto-suite/Giotto#313]
I am working with the 'clusterSpatialCorGenes' function and I was wondering if there was a method to optimize the 'k' parameter per sample? I am not sure if there is a metric in the 'spat_cor_netw_DT' you would feel comfortable with using in that case. I ask since the default 'k=8' leads to great results in some samples but less than meaningful results in others.

Thanks!
Joe

**Comment by gcyuan** [comment]
Hi Joe

There are a number of approaches people us to select k. The most popular ones are gap statistic and silhouette score. However, people often use these statistics as an informative guide rather than completely rely on them to pick the ‘best’ k because there are well-known cases they may not perform well. Not sure if this helps.

GC

**Comment by RubD** [comment]
Hi Joe,
In addition you could also take a look at the spatial co-expression heatmap and visually identify how many spatial co-expression modules you see (blocks along the diagonal). This will help you to get an idea which k-values you could try.

See the visium brain dataset [example](http://giottosuite.com/articles/mouse_visium_brain_220426.html#part-11-spatial-co-expression-modules).

Ruben
