### ISSUE TITLE
doLeidenSubCluster

### ISSUE THREAD

**Issue by onahman** [giotto-suite/Giotto#66]
It's a minor issue.
I am getting an error when running this function **doLeidenSubCluster**
_Error in calculateHVG(gobject = new("giotto", raw_exprs = new("dgCMatrix",  : 
  unused argument (difference_in_variance = 1)_
seems like an easy fix. 

Also, the usage example here:
https://rdrr.io/github/RubD/Giotto/man/doLeidenSubCluster.html
_doLeidenSubCluster(gobject)_
Doesn't work since it requires cluster_column to be specified.

**Comment by RubD** [comment]
Thanks for letting us know. I think this could actually be fixed by changing the defaults for the hvg_param parameter to:
`hvg_param = list(reverse_log_scale = T, difference_in_cov = 1, expression_values = 'normalized')`
I'll do more formal tests later this week. 

We haven't found a good and simple way for the individual usage examples, but we're working on that for in the next version.
