### ISSUE TITLE
doHMRF - segmentation fault

### ISSUE THREAD

**Issue by josicb16** [giotto-suite/Giotto#699]
Hi! I was trying to run functions for spatial domains identification using HMRF.
I am converting anndata object to giotto object.
I followed the tutorial https://rubd.github.io/Giotto_site/articles/tut11_giotto_hmrf.html and everything worked pretty well for the downsized sample of 5000 cells (observations). However, when I tried to run the same, for the whole sample, which has 59 704 observations, I get segmentation fault in the function doHMRF. 

I am not quite sure what could be the cause of this error and help would be appreciated.
Thank you.

PS. I get the warning about the allocation of matrix that has 9GB.
...

**System Information**

 - OS: Ubuntu
 - 512 GB RAM
 - Versions:
    - R 4.1.2
    - Giotto 3.3.0

**Comment by pacificma** [comment]
Hi @josicb16 Thank you for the feedback! 

Unfortunately we might not be able to detect and fix this issue in Giotto master branch quickly, since we are currently mainly working on the suite branch of Giotto, and there is an update on the HMRF method as well. I highly recommend you to try our new hmrf functions which has been already incorporated in Giotto 'suite_dev' branch which is a testing branch of Giotto suite. 

I have recently tried an example of similar size (57k cells x 351 genes) as yours and the HMRF function was running normally on it. It takes about 1 - 2hrs to finish on this data set , depending on the options you select in the function (top 20pc dim reduction of the spatial gene expressions or the selected 200 spatial gene expression as the input expression matrix). So I think the new function could work in your analysis.

If you could provide an email address I will forward you an draft tutorial for the new HMRF functions.

**Comment by josicb16** [comment]
Hi @pacificma. Thank you for the quick and detailed response. 

My email address is bojanajosic1998@gmail.com and tutorial would be greatly appreciated.

**Comment by josicb16** [comment]
Thank you! This is working properly!
