### ISSUE TITLE
Functions related to data table

### ISSUE THREAD

**Issue by Huimin721** [giotto-suite/Giotto#734]
Dear team,

Thanks so much for creating the outstanding package for analyzing spatial biology data. I have a question for the Giotto functions related to data tables. For example:
![image](https://github.com/drieslab/Giotto/assets/77763089/b668a3b1-0e9a-4749-aa32-66abb7a673e0)

Could I ask why you set the variables that are also column names as NULL at the beginning of the function? If we do not set them as NULL, will this cause any issues?

I would be very appreciate if you could share some insights! Thanks so much!

Best,
Huimin

**Comment by jiajic** [comment]
Hi @Huimin721,

Short answer: it is perfectly fine not to set these variables as NULL, and it should not affect the functionality of *data.table* if they are set or not.

The reason why we do it is a package development reason since *data.table* understands variable names as references to columns, but R CMD check sees them as undeclared variables. We set them as NULL in the beginning because this is the simplest way that we have found to prevent R CMD check from getting angry.

Best,
George

**Comment by Huimin721** [comment]
Hi George,@jiajic

Thanks so much! Just want o be super clear, in what circumstances, do people need to set some variables as NULL in a datatable?

Huimin

**Comment by jiajic** [comment]
Hi @Huimin721m

Probably the only situation in which people might want to set a variable that is used in a *data.table* command as NULL as we have done here is when they are developing an R package. R CMD check examines the whole package for errors and it picks up on the usage of variable **names** if they have not previously been assigned a value within the function scope and assumes that it is an error.

To give an example:
```
a = data.table::data.table(x = 1, y = 2, z = 3)
a[, y := 10]

# producing the following correct result
#    x  y z
# 1: 1 10 3

# however, this is what R CMD check expects that you just did
> y
Error: object 'y' not found
```
*We* understand that the `y` used here is used to refer to the 'y' column in data.table `a`, but R CMD check erroneously thinks that the code just used a variable `y` in the larger environment and that `y` does not exist and reports that there is an error.

We would set `y` to NULL (_It could be anything else. It's really just a placeholder_) in this situation so that R CMD check does not falsely report an error. It should have no effect on any _data.table_ or overall functionality of the script.

Best,
George

**Comment by Huimin721** [comment]
Hi @jiajic,

Thanks so much for the detailed reply. Could I understand it like this: 

data table is able to refer to columns in a way that looks like to refer a variable, but R CMD cannot recognize this. So when people refer column as if a variable like: 

DT[Fruit == "banana", ]
DT[, Count]

if there is no variables Fruit, Count in the global environment, then R CMD will not pass this.
In a word, the issue is datatable is able to refer columns in a way that looks like referring a variable, but R CMD cannot understand referring columns in this way.

Is my understanding correct? Many thanks again!

Best,
Huimin

**Comment by jiajic** [comment]
Hi @Huimin721,
Yes, that is exactly it. R CMD cannot understand it, so we add a dummy variable for Fruit and Count in the environment as a workaround.

Best,
George

**Comment by Huimin721** [comment]
Hi @jiajic,

Thanks so much for the detailed and clear answer!! And thanks again for the outstanding package!

Best,
Huimin
