### ISSUE TITLE
CreateGiottoImage x,y limits

### ISSUE THREAD

**Issue by jnmark** [giotto-suite/Giotto#80]
Hello,

Could you please provide some guidance on how to adjust the xmin, xmax, ymin, ymax values in CreateGiottoImage? Is it an offset or a multiplicative factor? I have been trying to play around with my values; I got the size of the images (visium and low-res tissue image) to be similar but there seems to be a lateral shift in the image regardless (the low-res image is always shifted to the right) and so it doesn't align. 

Thanks for the help!

**Comment by RubD** [comment]
Hi,

It is an offset and needs to be in the same units as your data coordinates, but I agree that it is now always easy to find the right alignment. To make this easier I have updated the **HOWTO** section on how to work with background images. See https://rubd.github.io/Giotto_site/articles/howto_images.html . I've added some additional examples to show how the offsets work and I simulated some potential shifts so that you could get some more insights on how to fix that.

Hope this helps,
R

**Comment by jnmark** [comment]
@RubD Thank you so much for that! It was indeed very helpful. Setting all offsets to 0 first and then tuning one at a time really made it very easy. Really appreciate your prompt help!

**Comment by RubD** [comment]
> @RubD Thank you so much for that! It was indeed very helpful. Setting all offsets to 0 first and then tuning one at a time really made it very easy. Really appreciate your prompt help!

Great! Happy I could help.
